version: "3.5"
services:
  web-scaffold:
    image: sndregistry.sondeosglobal.com/scaffold/web-scaffold
    container_name: web-scaffold
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.env.production:/www/.env.production
