version: "3"
services:
  skeleton-web:
    container_name: skeleton-web
    build: .
    ports:
      - "8000:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./.env.production:/www/.env.production
